version: '3'

services:
  rootconfig:
    build:
      context: ./root-config
      dockerfile: Dockerfile
    ports:
      - 9100:80
    

  clients:
    build:
      context: ./clients
      dockerfile: Dockerfile
    ports:
      - 9101:80

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 9102:80